### ISSUE TITLE
Cache the dune cache in CI

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-universe#1]
We should cache the Dune cache in the CI so that we can get faster builds. My experience with GitHub actions cache is that we will need to tar the entire cache directory and upload and download that for it to be fast.

**Comment by Alizter** [comment]
Actually the OCaml action has a dune cache option which I am assuming also gets cached by GitHub. I don't know how well it works however.

**Comment by Alizter** [comment]
For now I've enabled it, I will report back when I work out if it is working.

**Comment by Alizter** [comment]
Cache is enabled in the job but I cannot tell if it is working. Perhaps we need to enable cache for the entire project somewhere?

**Comment by ejgallego** [comment]
That's so interesting! I was assuming we'd have to wait for Dune to get network-base cache which we could then point to our own server.

You can test that by pushing a commit to for example a file on odd-order that nobody depends upon, then the rebuild should be quite fast.

Tho the size of the cache for Coq universe will likely be so large that we will hit trouble in GH.

Eventually we can setup a server on Inria to host the cache, but we need Dune to have networked cache.

**Comment by ejgallego** [comment]
I understand this is working :)
