### ISSUE TITLE
Vendor findlib and zarith

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-universe#2]
We are currently vendoring menhir in `lib/` and it seems to be working well. It would be good to have the same for findlib and zarith. At least with zarth I see that there is a dune branch https://github.com/ocaml/Zarith/pull/73 so it would be good to rebase and get that working. ocamlfind is a whole other story, and I don't know if there is dune support anywhere.

**Comment by ejgallego** [comment]
I don't want to vendor OCaml packages, that's a lot of work for little gain, except for Coq itself.

Once we push the composition stuff to Dune upstream, C-U can work well in a regular Opam or Nix env.

**Comment by Alizter** [comment]
OK, I've created an opam list in the makefile. When we wish to add opam deps, we add to the list. The CI will install that.
