### ISSUE TITLE
Check for performance increase by ocaml/dune#6555

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-universe#29]
We should test if https://github.com/ocaml/dune/pull/6555 has a visible affect on the build time.

**Comment by ejgallego** [comment]
Any news on this? I guess we can only check for zero-build times, or can we isolate dune CPU time from the full build? [That'd be cool]

**Comment by ejgallego** [comment]
Hi @Alizter , I'm closing this for now as I don't think we will get to it; feel free to reopen if you plan to work on it.

**Comment by Alizter** [comment]
Yeah, it is not important.
