### ISSUE TITLE
[CompCert] needs to depend on flocq theory

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-universe#3]
We need to update the dune file for compcert so that it has `(theories flocq)`.

**Comment by Alizter** [comment]
```
File "./CompCert/lib/IEEE754_extra.v", line 23, characters 0-131:
Error: Cannot find a physical path bound to logical path
Core with prefix Flocq.
```

```
File "./flocq/src/IEEE754/PrimFloat.v", line 24, characters 0-30:
Error: Cannot find a physical path bound to logical path
Int63 with prefix Coq.
```

**Comment by Alizter** [comment]
Added a fix.

**Comment by ejgallego** [comment]
Oh yes, good catch! I'm testing with Coq 8.15 installed in OPAM, until we fix the boot composition problem.

I just add coq-master to the list of ignored dirs, maybe we should push that change to the repos until we can bump the dune submodule.
