### ISSUE TITLE
[flocq] needs bumping

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-universe#5]
Flocq currently fails to find Int63 since it was renamed to Uint63 in coq master. Probably rebasing the dune branch is enough.

**Comment by Alizter** [comment]
I've bumped it and fixed some stuff in my fork: https://github.com/Alizter/flocq-fork

**Comment by ejgallego** [comment]
Yes, if we are serious about porting Flocq to dune we'd have to implement their config setup.

In general, in Coq's CI we often have configure scripts that all they do is to generate some code matching on the Coq version.

If we could implement `%{coq:version}` on the Dune side, porting that stuff would be straighforward?

**Comment by Alizter** [comment]
@ejgallego There is not much to patch, your version was just too far behind.

**Comment by ejgallego** [comment]
Umm, I was using the flocq-3 branch, you mean you updated to flocq-4 .

There is a bit of mess with that, we need to be careful.

**Comment by Alizter** [comment]
@ejgallego It appears that compcert is using flocq4

**Comment by ejgallego** [comment]
Yes! I was doing my build with 4.1 indeed, so I got flocq wrong but didn't realize I had no added the `theories` field.

We should setup the opam env in `_opam` for this to avoid problems of this kind.
