### ISSUE TITLE
Makefile doesn't work on Windows

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-universe#6]
Running the makefile on Windows we get the following error:
```
cd dune-ocaml && dune build --root . _build/install/default/bin/dune
Error: Don't know how to build _build/install/default/bin/dune
```

I guess for Windows we need to mention `dune.exe`.

**Comment by ejgallego** [comment]
I don't want to support windows.

**Comment by Alizter** [comment]
As we discussed elsewhere, supporting windows is "easy" so we might as well.
