### ISSUE TITLE
Revert to 7308fa26cbcf0c39f3f39e47d04908cf7daaeed6

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-universe#7]
Let's revert to 7308fa26cbcf0c39f3f39e47d04908cf7daaeed6 @ejgallego . The CI changes afterwards simply don't work the way I intended. I can salvage anything from then on myself and put it in a PR.

That commit should succeed IINM.

**Comment by ejgallego** [comment]
You got the lock on the repos, feel free to proceed as you wish!
